export interface Fund {
  id: number;
  fundName: string;
  schemeType: string;
  expenseRatio: string;
  aum: string;
  oneYearReturn: string;
  isHolding: boolean;
}

export const funds: Fund[] = [
  {
    id: 100001,
    fundName: "SBI Bluechip Fund - Direct Plan - Growth",
    schemeType: "Equity Large Cap",
    expenseRatio: "1.12",
    aum: "28943 Cr",
    oneYearReturn: "18.45",
    isHolding: true,
  },
  {
    id: 100002,
    fundName: "Axis Long Term Equity Fund - Direct Plan - Growth",
    schemeType: "ELSS",
    expenseRatio: "0.95",
    aum: "21654 Cr",
    oneYearReturn: "16.72",
    isHolding: false,
  },
  {
    id: 100003,
    fundName: "HDFC Mid-Cap Opportunities Fund - Direct Plan - Growth",
    schemeType: "Equity Mid Cap",
    expenseRatio: "1.23",
    aum: "19450 Cr",
    oneYearReturn: "22.18",
    isHolding: true,
  },
  {
    id: 100004,
    fundName: "Kotak Equity Arbitrage Fund - Direct Plan - Growth",
    schemeType: "Hybrid Arbitrage",
    expenseRatio: "0.68",
    aum: "12580 Cr",
    oneYearReturn: "7.35",
    isHolding: false,
  },
  {
    id: 100005,
    fundName: "ICICI Prudential Bluechip Fund - Direct Plan - Growth",
    schemeType: "Equity Large Cap",
    expenseRatio: "1.05",
    aum: "37520 Cr",
    oneYearReturn: "19.67",
    isHolding: false,
  },
  {
    id: 100006,
    fundName: "Nippon India Small Cap Fund - Direct Plan - Growth",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.36",
    aum: "24560 Cr",
    oneYearReturn: "28.55",
    isHolding: true,
  },
  {
    id: 100007,
    fundName: "Mirae Asset Emerging Bluechip Fund - Direct Plan - Growth",
    schemeType: "Equity Large & Mid Cap",
    expenseRatio: "1.15",
    aum: "19890 Cr",
    oneYearReturn: "21.32",
    isHolding: false,
  },
  {
    id: 100008,
    fundName: "Parag Parikh Flexi Cap Fund - Direct Plan - Growth",
    schemeType: "Flexi Cap",
    expenseRatio: "0.89",
    aum: "35670 Cr",
    oneYearReturn: "20.45",
    isHolding: true,
  },
  {
    id: 100009,
    fundName: "UTI Nifty Index Fund - Direct Plan - Growth",
    schemeType: "Index Fund",
    expenseRatio: "0.35",
    aum: "13400 Cr",
    oneYearReturn: "15.24",
    isHolding: false,
  },
  {
    id: 100010,
    fundName: "DSP Tax Saver Fund - Direct Plan - Growth",
    schemeType: "ELSS",
    expenseRatio: "1.17",
    aum: "17840 Cr",
    oneYearReturn: "17.91",
    isHolding: true,
  },
  {
    id: 100011,
    fundName: "Aditya Birla Sun Life Frontline Equity Fund",
    schemeType: "Equity Large Cap",
    expenseRatio: "1.21",
    aum: "26480 Cr",
    oneYearReturn: "18.02",
    isHolding: false,
  },
  {
    id: 100012,
    fundName: "Canara Robeco Bluechip Equity Fund",
    schemeType: "Equity Large Cap",
    expenseRatio: "0.89",
    aum: "17560 Cr",
    oneYearReturn: "19.67",
    isHolding: false,
  },
  {
    id: 100013,
    fundName: "Franklin India Focused Equity Fund",
    schemeType: "Equity Focused",
    expenseRatio: "1.42",
    aum: "9450 Cr",
    oneYearReturn: "14.23",
    isHolding: false,
  },
  {
    id: 100014,
    fundName: "Edelweiss Balanced Advantage Fund",
    schemeType: "Hybrid Dynamic Asset Allocation",
    expenseRatio: "1.09",
    aum: "16800 Cr",
    oneYearReturn: "11.78",
    isHolding: true,
  },
  {
    id: 100015,
    fundName: "Tata Equity P/E Fund",
    schemeType: "Equity Value Fund",
    expenseRatio: "1.25",
    aum: "8450 Cr",
    oneYearReturn: "19.92",
    isHolding: false,
  },
  {
    id: 100016,
    fundName: "HDFC Balanced Advantage Fund",
    schemeType: "Hybrid Balanced Advantage",
    expenseRatio: "1.02",
    aum: "30500 Cr",
    oneYearReturn: "12.45",
    isHolding: true,
  },
  {
    id: 100017,
    fundName: "Motilal Oswal Nifty 500 Fund",
    schemeType: "Index Fund",
    expenseRatio: "0.45",
    aum: "7200 Cr",
    oneYearReturn: "14.55",
    isHolding: false,
  },
  {
    id: 100018,
    fundName: "Baroda BNP Paribas Mid Cap Fund",
    schemeType: "Equity Mid Cap",
    expenseRatio: "1.33",
    aum: "5600 Cr",
    oneYearReturn: "24.76",
    isHolding: true,
  },
  {
    id: 100019,
    fundName: "Quant Small Cap Fund",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.48",
    aum: "6400 Cr",
    oneYearReturn: "29.02",
    isHolding: false,
  },
  {
    id: 100020,
    fundName: "ICICI Prudential Value Discovery Fund",
    schemeType: "Equity Value Fund",
    expenseRatio: "1.09",
    aum: "18000 Cr",
    oneYearReturn: "17.35",
    isHolding: true,
  },

  {
    id: 100021,
    fundName: "HDFC Flexi Cap Fund",
    schemeType: "Equity Flexi Cap",
    expenseRatio: "1.12",
    aum: "27500 Cr",
    oneYearReturn: "14.8",
    isHolding: false,
  },
  {
    id: 100022,
    fundName: "Nippon India Growth Fund",
    schemeType: "Equity Mid Cap",
    expenseRatio: "1.45",
    aum: "16300 Cr",
    oneYearReturn: "18.5",
    isHolding: true,
  },
  {
    id: 100023,
    fundName: "SBI Magnum Gilt Fund",
    schemeType: "Debt Long Duration",
    expenseRatio: "0.75",
    aum: "8600 Cr",
    oneYearReturn: "7.2",
    isHolding: false,
  },
  {
    id: 100024,
    fundName: "Axis Bluechip Fund",
    schemeType: "Equity Large Cap",
    expenseRatio: "1.18",
    aum: "34000 Cr",
    oneYearReturn: "13.9",
    isHolding: true,
  },
  {
    id: 100025,
    fundName: "ICICI Prudential Balanced Advantage Fund",
    schemeType: "Hybrid Dynamic Asset Allocation",
    expenseRatio: "1.05",
    aum: "54000 Cr",
    oneYearReturn: "12.1",
    isHolding: false,
  },
  {
    id: 100026,
    fundName: "Kotak Equity Arbitrage Fund",
    schemeType: "Hybrid Arbitrage",
    expenseRatio: "0.82",
    aum: "23000 Cr",
    oneYearReturn: "6.8",
    isHolding: false,
  },
  {
    id: 100027,
    fundName: "UTI Nifty 50 Index Fund",
    schemeType: "Index Fund",
    expenseRatio: "0.20",
    aum: "15300 Cr",
    oneYearReturn: "10.7",
    isHolding: true,
  },
  {
    id: 100028,
    fundName: "Parag Parikh Flexi Cap Fund",
    schemeType: "Equity Flexi Cap",
    expenseRatio: "0.89",
    aum: "44000 Cr",
    oneYearReturn: "16.3",
    isHolding: false,
  },
  {
    id: 100029,
    fundName: "Mirae Asset Emerging Bluechip Fund",
    schemeType: "Equity Large & Mid Cap",
    expenseRatio: "1.14",
    aum: "27000 Cr",
    oneYearReturn: "17.4",
    isHolding: true,
  },
  {
    id: 100030,
    fundName: "Tata Digital India Fund",
    schemeType: "Sectoral Technology",
    expenseRatio: "0.95",
    aum: "8200 Cr",
    oneYearReturn: "22.5",
    isHolding: false,
  },
  {
    id: 100031,
    fundName: "Franklin India Liquid Fund",
    schemeType: "Debt Liquid",
    expenseRatio: "0.27",
    aum: "17500 Cr",
    oneYearReturn: "6.2",
    isHolding: false,
  },
  {
    id: 100032,
    fundName: "Aditya Birla Sun Life Equity Advantage Fund",
    schemeType: "Equity Large & Mid Cap",
    expenseRatio: "1.38",
    aum: "12400 Cr",
    oneYearReturn: "15.9",
    isHolding: false,
  },
  {
    id: 100033,
    fundName: "SBI Small Cap Fund",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.52",
    aum: "22000 Cr",
    oneYearReturn: "20.6",
    isHolding: true,
  },
  {
    id: 100034,
    fundName: "HDFC Short Term Debt Fund",
    schemeType: "Debt Short Duration",
    expenseRatio: "0.45",
    aum: "11800 Cr",
    oneYearReturn: "7.4",
    isHolding: false,
  },
  {
    id: 100035,
    fundName: "Nippon India Value Fund",
    schemeType: "Equity Value",
    expenseRatio: "1.21",
    aum: "9600 Cr",
    oneYearReturn: "14.3",
    isHolding: false,
  },
  {
    id: 100036,
    fundName: "ICICI Prudential Technology Fund",
    schemeType: "Sectoral Technology",
    expenseRatio: "1.02",
    aum: "11200 Cr",
    oneYearReturn: "21.9",
    isHolding: true,
  },
  {
    id: 100037,
    fundName: "Axis Midcap Fund",
    schemeType: "Equity Mid Cap",
    expenseRatio: "1.33",
    aum: "20500 Cr",
    oneYearReturn: "17.8",
    isHolding: false,
  },
  {
    id: 100038,
    fundName: "Canara Robeco Bluechip Equity Fund",
    schemeType: "Equity Large Cap",
    expenseRatio: "0.85",
    aum: "18500 Cr",
    oneYearReturn: "12.4",
    isHolding: true,
  },
  {
    id: 100039,
    fundName: "DSP Small Cap Fund",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.47",
    aum: "16000 Cr",
    oneYearReturn: "19.8",
    isHolding: false,
  },
  {
    id: 100040,
    fundName: "Edelweiss Balanced Advantage Fund",
    schemeType: "Hybrid Dynamic Asset Allocation",
    expenseRatio: "0.97",
    aum: "27500 Cr",
    oneYearReturn: "11.3",
    isHolding: true,
  },
  {
    id: 100041,
    fundName: "ICICI Prudential Equity & Debt Fund",
    schemeType: "Hybrid Aggressive",
    expenseRatio: "1.04",
    aum: "32000 Cr",
    oneYearReturn: "13.6",
    isHolding: false,
  },
  {
    id: 100042,
    fundName: "Motilal Oswal Nifty 500 Fund",
    schemeType: "Index Fund",
    expenseRatio: "0.22",
    aum: "4300 Cr",
    oneYearReturn: "10.4",
    isHolding: true,
  },
  {
    id: 100043,
    fundName: "Union Small Cap Fund",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.43",
    aum: "5200 Cr",
    oneYearReturn: "19.3",
    isHolding: false,
  },
  {
    id: 100044,
    fundName: "Tata Balanced Advantage Fund",
    schemeType: "Hybrid Dynamic Asset Allocation",
    expenseRatio: "0.88",
    aum: "7400 Cr",
    oneYearReturn: "10.9",
    isHolding: false,
  },
  {
    id: 100045,
    fundName: "HDFC Small Cap Fund",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.50",
    aum: "21000 Cr",
    oneYearReturn: "22.1",
    isHolding: true,
  },
  {
    id: 100046,
    fundName: "Quant Flexi Cap Fund",
    schemeType: "Equity Flexi Cap",
    expenseRatio: "0.92",
    aum: "12500 Cr",
    oneYearReturn: "18.7",
    isHolding: false,
  },
  {
    id: 100047,
    fundName: "UTI Banking and Financial Services Fund",
    schemeType: "Sectoral Banking",
    expenseRatio: "1.25",
    aum: "6800 Cr",
    oneYearReturn: "15.5",
    isHolding: false,
  },
  {
    id: 100048,
    fundName: "Sundaram Mid Cap Fund",
    schemeType: "Equity Mid Cap",
    expenseRatio: "1.37",
    aum: "7800 Cr",
    oneYearReturn: "16.9",
    isHolding: false,
  },
  {
    id: 100049,
    fundName: "ICICI Prudential Infrastructure Fund",
    schemeType: "Sectoral Infrastructure",
    expenseRatio: "1.28",
    aum: "10200 Cr",
    oneYearReturn: "20.2",
    isHolding: true,
  },
  {
    id: 100050,
    fundName: "Kotak Small Cap Fund",
    schemeType: "Equity Small Cap",
    expenseRatio: "1.46",
    aum: "13200 Cr",
    oneYearReturn: "18.2",
    isHolding: false,
  },
];
